### ISSUE TITLE
How to create your own multi-language model?

### ISSUE THREAD

**Issue by erikvullings** [semi-technologies/t2v-transformers-models#30]
Is it possible to create a multi-language transformer, selecting your own languages? And if so, how can it be done? Also, could we update or enhance an existing language, e.g. by adding know synonyms?

**Comment by bobvanluijt** [comment]
Yes, this is possible.

You can use [this](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2) model.

In the [weaviate configurator](https://weaviate.io/developers/weaviate/current/getting-started/installation.html#customize-your-weaviate-setup) you can select it following: `with modules -> text -> text2vec-transformers -> sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`

Going to close this issue, feel free to continue the discussion on our [Slack channel](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw)
